title: Ian Marquette - Product Designer
email: ian@ianmarquette.conm
description: > # this means to ignore newlines until "baseurl:"
  Ian Marquette is a product designer based in Nova Scotia, Canada.

baseurl: "" # the subpath of your site, e.g. /blog

url: "http://ianmarquette.com" # the base hostname & protocol for your site

